#!/usr/bin/python3
      2 
      3 import sys
      4 import datetime
      5 
      6 template = """# {date}
      7 
      8 ## Daily Checklist
      9 
     10 * [ ] Leetcode
     11 
     12 
     13 ## Todo
     14 
     15 
     16 
     17 ## ESP
     18 
     19 ### Effort
     20 
     21 
     22 
     23 ### Success
     24 
     25 
     26 
     27 ### Progress
     28 
     29 
     30 
     31 ## Notes
     32 """
     33 
     34 
     35 date = datetime.date.today()
     36 if len(sys.argv) < 2:
     37     date = sys.argv[1].rsplit("/", 1)[1];
     38     date = date.split(".", 1)[0];
     39 
     40 print(template.format(date = date));
